
  <!doctype html>
<html lang="en">
  <head>
    <title>Morning side suitesdsd,Sandton South Africa. Rooms and Suites from ₦30,000</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content=" Best hotel room rate in Sandton from  ₦30,000 at Morning side suitesdsd">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900|Rubik:300,400,700" rel="stylesheet">
    <link rel="icon" type="image/png" href="../images/hotel-logo.png">
    <link rel="stylesheet" href="../assets/css/bootstrap.css">
    <link rel="stylesheet" href="../assets/css/animate.css">
    <link rel="stylesheet" href="../assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="../assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="../assets/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="../assets/css/magnific-popup.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="canonical" href="https://Morningsidesuites.com/en/index.php" />


 
    <!-- Theme Style -->
    <link rel="stylesheet" href="../assets/css/style.css">
    <!-- Google font -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
  <!-- Custom stlylesheet -->
  <link type="text/css" rel="stylesheet" href="../assets/css/404.css" />
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  
  </head>
  <body>
    
    <header role="banner">
     
      
     
      <nav class="navbar navbar-expand-md navbar-dark bg-light">
        <div class="container">
              <a class="navbar-brand" href="../index.php">
              <img src="../images/hotel-logo.png" width="200" height="120" class="d-inline-block align-top" alt="Morning side suitesdsd" title="Morning side suitesdsd">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
            <ul class="navbar-nav ml-auto pl-lg-5 pl-0">
              <li class="nav-item " style=""> 
                <a class="nav-link active" href="index.php" style="color:#f4e181;color: #fff; font-weight: bold">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="hotel-rooms/index.php" id="rooms-categories" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="hotel-rooms" style="color:#f4e181">Rooms</a>
                <div class="dropdown-menu" aria-labelledby="rooms-categories">
                  <a class="dropdown-item" href="hotel-rooms/index.php" style="color:#f4e181;">All Rooms</a>
                   <a class="dropdown-item" href="hotel-rooms/presidential-suite.php" style="color:#f4e181;"> presidential suite                              </a>                         <a class="dropdown-item" href="hotel-rooms/business-suite.php" style="color:#f4e181;"> business suite                              </a>                         <a class="dropdown-item" href="hotel-rooms/classic-suite.php" style="color:#f4e181;"> classic suite                              </a>                                                            
                </div>
              </li>
              <li class="nav-item">

                <a class="nav-link " href="facilities/index.php" style="color:#f4e181" >Facilities</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="gallery/index.php" style="color:#f4e181;">Gallery</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " href="contact-us/index.php" style="color:#f4e181;">Contact</a>
              </li>
               
            </ul>
            
          </div>
        </div>
      </nav>
   
        
    </header>
   


    <!-- END header -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "article",
  "name" : "Morning side suitesdsd",
  "dateModified" : "2019-07-18",
  "author" : {
    "@type" : "Person",
    "name" : "Guests"
  },
  "mainEntityOfPage": {
         "@type": "WebPage",
         "@id": "Morningsidesuites.com"
         },
  "headline" : "Morning side suitesdsd",
  "datePublished" : "2019-07-18 or 2019-07-27T10:31",
  "image" : "../images/classic2.jpg",
  "articleBody" : "Within the Central Business District of Abuja is The Statement Hotel. A luxuriously built and tastefully furnished hotel standing head and shoulders above others in the hospitality industry. We take pride in taking giant strides in redefining the hospitality sector. We are The Statement Hotel. We are your ideal one stop destination in Abuja. We offer unrivaled hospitality services at astonishingly give away rates. Our facilities are top notch. A beauty to behold, we radiate glamour on every side. From our exterior to the lounge, meet our excellent and homely receptionists, down to our rooms, you are up for a lifetime treat. Nobody does it better than we do. We have made our mark and thus we have written a bold statement. Our mighty edifice easily makes other hotels in Abuja look like childs play. Our service remains top notch. We have a beautiful blend of African, Latin and contemporary flavors. Our location is in one of the best piece of real estate in West Africa. When conducting business in Abuja, staying at the statement hotel makes a lot of sense.",
  "publisher": {
        "@type": "Organization",
        "name": "Morning side suitesdsd",
        "logo": {
            "@type": "ImageObject",
            "name": "Morning side suitesdsd",
            "width": "100",
            "height": "100",
            "url": "../images/hotel-logo.png"
        },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "ratingValue" : "4",
    "bestRating" : "5",
    "ratingCount" : "43"
  }
}
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Morning side suitesdsd",
  "image" : "../images/hotel-logo.png",
  "telephone" : "(+234) 8032-749-921",
  "email" : "fredrickoladipupo@gmail.com",
  "priceRange" : "₦30,000 - ₦80,000",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "otegbade street ejigbo lagos",
    "addressLocality" : "otegbade street ejigbo lagos",
    "addressRegion" : "otegbade street ejigbo lagos"
  },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "ratingValue" : "4",
    "bestRating" : "5",
    "worstRating" : "3",
    "ratingCount" : "74"
  }
  
}
</script>
<script type="application/ld+json">
        {
      "@context": "https://schema.org/",
      "@type": "Product",
      "name": "classic suite from ₦30,000 at Morning side suitesdsd",
      "image": 
        "../images/presidential3.jpg",
      "brand": {
        "@type": "Thing",
        "name": ""
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.4",
        "ratingCount": "89"
      },
      "offers": {
        "@type": "AggregateOffer",
        "lowPrice": "30000",
        "highPrice": "80000",
        "priceCurrency": "NGN"
      }
    }
  
</script>
<section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(../images/main_image.jpg);")>
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-12 text-center">
            <div class="mb-5 element-animate" >
              <h1  >Welcome To Our Luxury Rooms</h1>
              <p >Discover our world's #1 Luxury Room For VIP.</p>
              
            </div>
                <div class="row justify-content-center" >
                  <div class="col-md-auto">
                    <nav class=" breadcrumb_white text-center">
                      <ol class="breadcrumb justify-content-center" itemscope itemtype="https://schema.org/BreadcrumbList" >
                        <li class="breadcrumb_for_list_Items" itemprop="itemListElement" itemscope
          itemtype="https://schema.org/ListItem"><a class='breadcrumb_icon' href="index.php" itemtype="https://schema.org/Thing"
           itemprop="item"><span itemprop="name">&nbsp;Home &nbsp;</span></a>
                            <meta itemprop="position" content="1" />
                        </li>
                          
                      </ol>
                    </nav>
                  </div>
                </div>
                <p ><a href="" class="btn btn-primary">Check Availability</a></p>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    <section class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="heading-wrap  element-animate">
              <h2 class="heading text-center">Stay and Enjoy</h2>
              <p class="mb-5"> Within the Central Business District of Abuja is The Statement Hotel. A luxuriously built and tastefully furnished hotel standing head and shoulders above others in the hospitality industry. We take pride in taking giant strides in redefining the hospitality sector. We are The Statement Hotel. We are your ideal one stop destination in Abuja. We offer unrivaled hospitality services at astonishingly give away rates. Our facilities are top notch. A beauty to behold, we radiate glamour on every side. From our exterior to the lounge, meet our excellent and homely receptionists, down to our rooms, you are up for a lifetime treat. Nobody does it better than we do. We have made our mark and thus we have written a bold statement. Our mighty edifice easily makes other hotels in Abuja look like childs play. Our service remains top notch. We have a beautiful blend of African, Latin and contemporary flavors. Our location is in one of the best piece of real estate in West Africa. When conducting business in Abuja, staying at the statement hotel makes a lot of sense. </p>
              
            </div>
          </div>
          <div class="col-md-6">
            <img src="../images/pool.jpg" alt="Sandton" title="Swimming Pool" class="img-md-fluid">
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    <section class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
              <h2 class="heading">Featured Rooms</h2>
          </div>
        </div>
        <div class="row ">
          <div class="col-md-7">
            <div class="media d-block room mb-0">
              <a href="hotel-rooms/presidential-suite.php"  class="media d-block room bg first-room">
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                <img src="../images/presidential3.jpg" alt="This room has 2 rooms, 1 parlor and 1 dining. Yes! Come experience the presidential treat in our presidential suite. It?s a feeling better experienced than imagined. With you in our presidential suite, you are nothing but a king. Our presidential suite offers just more than you would possibly ask. Each room is an exact replica of the other. Guests that want to stay with their families usually prefer the presidential room, especially when its one big family event, and everybody wants to stay in the same room. When you request for the presidential suite, you get our premium suite, with nothing but the best." title="presidential suite" class="img-fluid">
                <div style="position: absolute;bottom: 0px; width: 100%; background-color:rgba(0,0,0,0.5); padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      
                      ₦80,000 
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px;  ">Presidential suite </strong>
                      <div  style=" margin-left: 10px;margin-top:0px; padding-top: 0px;color: #fff; " class="mt-0">  <small>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                        </small>
                      </div>
                    </span>
                  </div>
                  
                </div>
              </div>
              
              <div class="media-body">
                
                
                
                <div class="clearfix">
                          <div class="col-sm-8 float-left">
                            <h3 class="mt-0"><a href="hotel-rooms/presidential-suite/index.php">Presidential suite </a></h3>
                              <ul class="room-specs">
                                <li><span class="ion-ios-people-outline"></span> 2 Guests</li>
                                <li><span class="ion-ios-crop"></span> 22 ft <sup>2</sup></li>
                                 <li><i class="fa fa-bed" aria-hidden="true"></i> &nbsp; Beds</li> 
                              </ul>
                                
                                    <button type="button" class="btn btn-primary btn-sm ">Check Availability</button>
                              
                          </div>
                          <div class="col-sm-4 float-right" style=" margin-top: 30px">
                            <P>
                              This room has 2 rooms, 1 parlor and 1 dining.<a href="hotel-rooms/index.php">..continue..</a> 
                            </P>
                          </div>
                    
                </div>
              </div>
              </a>
            </div>
          </div>
          <div class="col-md-5 room-thumbnail-absolute">
            <a href="hotel-rooms/business-suite.php" class="media d-block room bg first-room" >
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                 
                      <img src="../images/business.jpg" alt="Our business suites consists of a room and a sitting room. Exclusively reserved for guests who crave for the unique provisions only associated with us providing your hospitality needs. Just between the sitting room and the bedroom is an interconnecting door whose access can be restricted by the occupants. Also in the bedroom is a small sitting area, able to seat two persons. Stay in our business suites and enjoy daily supply of fresh toiletries, excellent room service, free access to high speed internet, complimentary breakfast, and lots more. It?s indeed a total package for the business minded individual." title="business suite" class="img-fluid">

                <div style="position: absolute;bottom: 0px; width: 100%;background-color:rgba(0,0,0,0.5); padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px;  ">Business suite</strong>
                    </span>
                  </div>
                    
                  
                </div>
              </div>
                    
            </a>
            <a href="hotel-rooms/classic-suite.php" class="media d-block room bg first-room" >
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                 
                      <img src="../images/classic.jpg" alt="Classic not just by name. Our classic rooms boast of a wide array of truly first class quality. The interior is just superb, leaving our guests in awe as to what is on offer. The colors, wall decorations and paintings reflect great works of art. There is the presence of a sitting area next to a king size bed in the fully air-conditioned classic room. The classic rooms come with an intercom which means our guests are one dial away from their requests been met. Our guests also have access to high speed internet and other hotel facilities including but not limited to the swimming pool, lounge, and the likes. For every night spend in our classic room, a complimentary breakfast is guaranteed. This is simply putting you first!" title="classic suite" class="img-fluid">

                <div style="position: absolute;bottom: 0px;background-color:rgba(0,0,0,0.5); width: 100%; padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px; ">Classic suite</strong>
                    </span>
                  </div>
                    
                  
                </div>
              </div>
                    
            </a>
            
          </div>
        </div>
      </div>
    </section>
   
    
    <section class="section-cover" data-stellar-background-ratio="0.5" style="color: black; background-image: url(../images/presidential2.jpg) ;">
      <div class="container">
        <div class="row justify-content-center align-items-center intro">
          <div class="col-md-9 text-center element-animate">
            <h2>Relax and Enjoy your Holiday</h2>
            <p class="lead mb-5"></p>
            <div class="btn-play-wrap"><a href="https://vimeo.com/channels/staffpicks/93951774" class="btn-play popup-vimeo "><span class="ion-ios-play"></span></a></div>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    
    <section class=" bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
            <h2 class="heading">Gallery</h2>
          </div>
        </div>
        <div class="row ">
          <div class="col-md-4"  >            <div class="post-entry">
              <a href="gallery/index.php"><img src="../images/ruthy.jpg" alt="You can never be hungry at The Statement Hotel. Our restaurant, Ruthy Savour signature will feed you fat. We are experienced in the delicate art of preparing meals, with a touch of art and the professionalism of international chefs. When you step into our restaurant, you immediately appreciate the time and effort we took to prepare not just our environment, but our meals. From our professional staff to our well lit environment; the interior decor to the taste of the food. Everything is tailor made to maximize your satisfaction. "  title="Ruthy Savour Signature" class="img-fluid"></a>
              <div class="body-text">
                <div class="category">Ruthy Savour Signature</div>
                <h3 class="mb-3"><a href="gallery/index.php">Ruthy Savour Signature</a></h3>
                <p class="mb-4">
                  You can never be hungry at The Statement Hote<a href="gallery/index.php">..continue..</a> 
                </p>
              </div>
            </div>
         </div>              <div class="col-md-4"  >            <div class="post-entry">
              <a href="gallery/index.php"><img src="../images/business.jpg" alt="Our business suites consists of a room and a sitting room. Exclusively reserved for guests who crave for the unique provisions only associated with us providing your hospitality needs. Just between the sitting room and the bedroom is an interconnecting door whose access can be restricted by the occupants. Also in the bedroom is a small sitting area, able to seat two persons. Stay in our business suites and enjoy daily supply of fresh toiletries, excellent room service, free access to high speed internet, complimentary breakfast, and lots more. It?s indeed a total package for the business minded individual."  title="Business Suite" class="img-fluid"></a>
              <div class="body-text">
                <div class="category">Business Suite</div>
                <h3 class="mb-3"><a href="gallery/index.php">Business Suite</a></h3>
                <p class="mb-4">
                  Our business suites consists of a room and a <a href="gallery/index.php">..continue..</a> 
                </p>
              </div>
            </div>
         </div>              <div class="col-md-4"  >            <div class="post-entry">
              <a href="gallery/index.php"><img src="../images/conference.jpg" alt="This halls are ideal for large and small groups. Our halls can sit over 120 persons in a banquet setting and up to two hundred in a cocktail setting. Collins mini hall is available for an NGO event, training or meeting. The hall is fully air-conditioned and have the added benefit of the restaurant serving our guests upon demand. It is all about you obviously. There is equally the provision of electronic gadgets to give the much need support to ensure a smooth event is held. We have your logistics all covered. All that is needed is to tell us your requirement, and we will handle the rest. "  title="Our conference hall" class="img-fluid"></a>
              <div class="body-text">
                <div class="category">Our Conference Hall</div>
                <h3 class="mb-3"><a href="gallery/index.php">Our Conference Hall</a></h3>
                <p class="mb-4">
                  This halls are ideal for large and small grou<a href="gallery/index.php">..continue..</a> 
                </p>
              </div>
            </div>
         </div>              
          
         
         
          <div class="container">
            <div class="row justify-content-md-center">
              <div class="col-md-auto">
                <p><a href="gallery/index.php" class="btn btn-primary btn-sm">View All Gallery</a></p>
              </div>
            </div>
        </div>
        </div>
        
      </div>
    
    </section>
    <!-- END section -->
  <section class=" bg-light">
      <div class="container">
      <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
            <h2 class="heading">Facilities</h2>
          </div>
        </div>
  <div class="mt-5">
<div class="container">
            <div class="row ">
              <div class="col-md-4" style=" margin-top:20px;margin-bottom: 10px;">            <div class="post-entry mh-100 d-inline-block p-2 " style="height:400px; background-color: #fff";>
              <a href="facilities/index.php"><img  src="../images/ruthy.jpg"  class="img-fluid" alt="You can never be hungry at The Statement Hotel. Our restaurant, Ruthy Savour signature will feed you fat. We are experienced in the delicate art of preparing meals, with a touch of art and the professionalism of international chefs. When you step into our restaurant, you immediately appreciate the time and effort we took to prepare not just our environment, but our meals. From our professional staff to our well lit environment; the interior decor to the taste of the food. Everything is tailor made to maximize your satisfaction. " title="Ruthy Savour Signature"></a>
              <div class="body-text" style="height: 100px; padding: 0px;">
                <div class="category">Ruthy Savour Signature</div>
                <h3 class=""><a href="facilities/index.php">Ruthy Savour Signature</a></h3>
                <p class="mb-4" style="height:100px;background-color: #fff"> You can never be hungry at The Statement Hote<a href="facilities/index.php">..continue..</a></p>
              </div>
            </div>
          </div><div class="col-md-4" style=" margin-top:20px;margin-bottom: 10px;">            <div class="post-entry mh-100 d-inline-block p-2 " style="height:400px; background-color: #fff";>
              <a href="facilities/index.php"><img  src="../images/ruthy.jpg"  class="img-fluid" alt="You can never be hungry at The Statement Hotel. Our restaurant, Ruthy Savour signature will feed you fat. We are experienced in the delicate art of preparing meals, with a touch of art and the professionalism of international chefs. When you step into our restaurant, you immediately appreciate the time and effort we took to prepare not just our environment, but our meals. From our professional staff to our well lit environment; the interior decor to the taste of the food. Everything is tailor made to maximize your satisfaction. " title="Ruthy Savour Signature"></a>
              <div class="body-text" style="height: 100px; padding: 0px;">
                <div class="category">Ruthy Savour Signature</div>
                <h3 class=""><a href="facilities/index.php">Ruthy Savour Signature</a></h3>
                <p class="mb-4" style="height:100px;background-color: #fff"> You can never be hungry at The Statement Hote<a href="facilities/index.php">..continue..</a></p>
              </div>
            </div>
          </div>               


              
          
          <a href="facilities/index.php">
              <div class="col-md-4" style=" min-height: 400px; position: relative; background-image: url(../images/conference.jpg); margin: 20px 0px 40px 0px; padding: 0px 15px 0px 15px;">
                
                  <div style="position: absolute;font-size:24px; font-size: 24px;font-weight: 900;top: 50%;left: 25%; width: 100% ">
                    <a href="facilities/index.php" style="color: #fff">
                           <i class="fa fa-plus" ></i><strong > &nbsp;See more</strong>
                    </a>
                </div>
          </a>      
                
             
              </div>
        </div>
      </div>
      </div>
    </section>

<footer class="site-footer">
        <div class="container">
          <div class="row mb-5">
            <div class="col-md-6">
              <div class="widget widget-address">
                                  <h5 class="footer-widget-title decorator">Address</h5>
                                  <div class="address"> 
                                      <p> <i class="fa fa-map-marker" aria-hidden="true">&nbsp;</i>&nbsp; otegbade street ejigbo lagos</p>
                                  </div>
                                   <div>
                                      <p><i class="fa fa-envelope " aria-hidden="true"></i> <a href="mailto:booking@statementhotel.com">&nbsp; fredrickoladipupo@gmail.com</a></p>
                                  </div>  
                                  <div>
                                      <p>Reservations:<br /><i class="fa fa-phone" aria-hidden="true"></i> <a href="tel:+234.0706-815-1023">&nbsp; (+234) 8032-749-921</a></p>
                                  </div> 
                                     
              </div>
            </div>
            <div class="col-md-4">
              <h3>Connect With Us</h3>
              <p>We are socialized. Follow us</p>
              <p>
                <a href="facebook.com" class="pl-0 p-3"><span class="fa fa-facebook"></span></a>
                <a href="twiiter.com" class="p-3"><span class="fa fa-twitter"></span></a>
                <a href="instagram.com" class="p-3"><span class="fa fa-instagram"></span></a>
                <a href="<br />
<b>Notice</b>:  Undefined index: linkedin in <b>/opt/lampp/htdocs/scheme2/includes/footer.php</b> on line <b>26</b><br />
" class="p-3"><span class="fa fa-linkedin"></span></a>
                <a href="dwdwww" class="p-3"><span class="fa fa-youtube-play"></span></a>
              </p>
            </div>
            <div class="col-md-2">
              <h3>Connect With Us</h3>
              <p>Get Updates</p>
              <form action="#" class="subscribe">
                <div class="form-group">
                  <button type="submit"><span class="ion-ios-arrow-thin-right"></span></button>
                  <input type="email" class="form-control" placeholder="">
                </div>
                
              </form>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-7 text-center">
              
              <p class="copyright-text">Designed and Managed by <a href="http://www.primeroyalhospitality.com?source="statementhotel.com >Prime Royal Hospitality Services Ltd. </a></p>
                         
            </div>
          </div>
        </div>
      </footer>
      <!-- END footer -->
      
      <!-- loader -->
      <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>
      <script src="../assets/js/jquery-3.2.1.min.js"></script>
      <script src="../assets/js/jquery-migrate-3.0.0.js"></script>
      <script src="../assets/js/popper.min.js"></script>
      <script src="../assets/js/bootstrap.min.js"></script>
      <script src="../assets/js/owl.carousel.min.js"></script>
      <script src="../assets/js/jquery.waypoints.min.js"></script>
      <script src="../assets/js/jquery.stellar.min.js"></script>
      <script src="../assets/js/jquery.magnific-popup.min.js"></script>
      <script src="../assets/js/magnific-popup-options.js"></script>
      <script src="../assets/js/main.js"></script>
    </body>
  </html>
  