  <?php
  ob_start();
   $main = 1;

  ?>

  <!doctype html>
<html lang="en">
  <head>
    <title><?php echo settings($id)['hotel_name'] .",". settings($id)['city'] ." ". settings($id)['country']. ". Rooms and Suites from ₦".number_format(room($id)[2][3])?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content=" Best hotel room rate in <?php echo settings($id)['city'] ?> from  <?php echo '₦' .number_format(room($id)[2][3]) ?> at <?php echo settings($id)['hotel_name'] ?>">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900|Rubik:300,400,700" rel="stylesheet">
    <link rel="icon" type="image/png" href="images/<?php echo settings($id)['logo'] ?>">
    <link rel="stylesheet" href="assets/css/bootstrap.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="assets/fonts/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/fonts/fontawesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/magnific-popup.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="canonical" href="<?php echo 'https://'.settings($id)['domain']?>/en/index.php" />


 
    <!-- Theme Style -->
    <link rel="stylesheet" href="assets/css/style.css">
    <!-- Google font -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">
  <!-- Custom stlylesheet -->
  <link type="text/css" rel="stylesheet" href="assets/css/404.css" />
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  
  </head>
  <body>
    
    <header role="banner">
     
      <?php 
  
       include("includes/navbar1.php");

    ?>
    
    </header>
   


    <!-- END header -->
    <script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "article",
  "name" : "<?php echo settings($id)['hotel_name'] ?>",
  "dateModified" : "2019-07-18",
  "author" : {
    "@type" : "Person",
    "name" : "Guests"
  },
  "mainEntityOfPage": {
         "@type": "WebPage",
         "@id": "<?php echo settings($id)['domain'] ?>"
         },
  "headline" : "<?php echo settings($id)['hotel_name'] ?>",
  "datePublished" : "2019-07-18 or 2019-07-27T10:31",
  "image" : "images/<?php echo room($id)[7][3][2] ?>",
  "articleBody" : "<?php echo settings($id)['description'] ?>",
  "publisher": {
        "@type": "Organization",
        "name": "<?php echo settings($id)['hotel_name'] ?>",
        "logo": {
            "@type": "ImageObject",
            "name": "<?php echo settings($id)['hotel_name'] ?>",
            "width": "100",
            "height": "100",
            "url": "images/<?php echo settings($id)['logo'] ?>"
        },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "ratingValue" : "4",
    "bestRating" : "5",
    "ratingCount" : "43"
  }
}
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "<?php echo settings($id)['hotel_name'] ?>",
  "image" : "images/<?php echo settings($id)['logo'] ?>",
  "telephone" : "<?php echo settings($id)['hotline']  ?>",
  "email" : "<?php echo settings($id)['frontoffice_mail']  ?>",
  "priceRange" : "<?php echo '₦'. number_format(room($id)[2][3]) ?> - <?php echo "₦". number_format(room($id)[2][1]) ?>",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "<?php echo settings($id)['address1']  ?>",
    "addressLocality" : "<?php echo settings($id)['address1']  ?>",
    "addressRegion" : "<?php echo settings($id)['address1']  ?>"
  },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "ratingValue" : "4",
    "bestRating" : "5",
    "worstRating" : "3",
    "ratingCount" : "74"
  }
  
}
</script>
<script type="application/ld+json">
        {
      "@context": "https://schema.org/",
      "@type": "Product",
      "name": "<?php echo room($id)[1][3]?> from <?php echo "₦".number_format(room($id)[2][3]) ?> at <?php echo settings($id)['hotel_name'] ?>",
      "image": 
        "images/<?php echo room($id)[7][1][3] ?>",
      "brand": {
        "@type": "Thing",
        "name": "<?php settings($id)['hotel_name'] ?>"
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.4",
        "ratingCount": "89"
      },
      "offers": {
        "@type": "AggregateOffer",
        "lowPrice": "<?php echo room($id)[2][3] ?>",
        "highPrice": "<?php echo room($id)[2][1] ?>",
        "priceCurrency": "NGN"
      }
    }
  
</script>
<section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(images/<?php echo settings($id)['main_img']; ?>);")>
      <div class="container">
        <div class="row align-items-center site-hero-inner justify-content-center">
          <div class="col-md-12 text-center">
            <div class="mb-5 element-animate" >
              <h1  >Welcome To Our Luxury Rooms</h1>
              <p >Discover our world's #1 Luxury Room For VIP.</p>
              
            </div>
                <div class="row justify-content-center" >
                  <div class="col-md-auto">
                    <nav class=" breadcrumb_white text-center">
                      <ol class="breadcrumb justify-content-center" itemscope itemtype="https://schema.org/BreadcrumbList" >
                        <li class="breadcrumb_for_list_Items" itemprop="itemListElement" itemscope
          itemtype="https://schema.org/ListItem"><a class='breadcrumb_icon' href="index.php" itemtype="https://schema.org/Thing"
           itemprop="item"><span itemprop="name">&nbsp;Home &nbsp;</span></a>
                            <meta itemprop="position" content="1" />
                        </li>
                          
                      </ol>
                    </nav>
                  </div>
                </div>
                <p ><a href="" class="btn btn-primary">Check Availability</a></p>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    <section class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="heading-wrap  element-animate">
              <h2 class="heading text-center">Stay and Enjoy</h2>
              <p class="mb-5"> <?php echo settings($id)['description'] ?> </p>
              
            </div>
          </div>
          <div class="col-md-6">
            <img src="images/<?php echo fac($id)[7][3][1] ?>" alt="<?php echo fac($id)[4][3] ?>" title="<?php echo fac($id)[1][3] ?>" class="img-md-fluid">
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    <section class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
              <h2 class="heading">Featured Rooms</h2>
          </div>
        </div>
        <div class="row ">
          <div class="col-md-7">
            <div class="media d-block room mb-0">
              <a href="hotel-rooms/<?php echo strtolower(str_replace(" ","-", room($id)[1][1]))  ?>.php"  class="media d-block room bg first-room">
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                <img src="images/<?php echo room($id)[7][1][3] ?>" alt="<?php echo room($id)[4][1] ?>" title="<?php echo room($id)[1][1] ?>" class="img-fluid">
                <div style="position: absolute;bottom: 0px; width: 100%; background-color:rgba(0,0,0,0.5); padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      
                      <?php echo "₦".number_format(room($id)[2][1]) ?> 
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px;  "><?php echo ucfirst(room($id)[1][1]) ?> </strong>
                      <div  style=" margin-left: 10px;margin-top:0px; padding-top: 0px;color: #fff; " class="mt-0">  <small>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                          <i class="fa fa-star" aria-hidden="true"></i>
                        </small>
                      </div>
                    </span>
                  </div>
                  
                </div>
              </div>
              
              <div class="media-body">
                
                
                
                <div class="clearfix">
                          <div class="col-sm-8 float-left">
                            <h3 class="mt-0"><a href="hotel-rooms/<?php echo strtolower(str_replace(" ","-", room($id)[1][1]))  ?>/index.php"><?php echo ucfirst(room($id)[1][1]);  ?> </a></h3>
                              <ul class="room-specs">
                                <li><span class="ion-ios-people-outline"></span> 2 Guests</li>
                                <li><span class="ion-ios-crop"></span> 22 ft <sup>2</sup></li>
                                 <li><i class="fa fa-bed" aria-hidden="true"></i> &nbsp; Beds</li> 
                              </ul>
                                
                                    <button type="button" class="btn btn-primary btn-sm ">Check Availability</button>
                              
                          </div>
                          <div class="col-sm-4 float-right" style=" margin-top: 30px">
                            <P>
                              <?php
                                $text = room($id)[4][1];
                                $max =45;
                                $append= '<a href="hotel-rooms/index.php">..continue..</a>';
                                echo substr($text, 0, $max).$append;
                              ?> 
                            </P>
                          </div>
                    
                </div>
              </div>
              </a>
            </div>
          </div>
          <div class="col-md-5 room-thumbnail-absolute">
            <a href="hotel-rooms/<?php echo strtolower(str_replace(" ","-", room($id)[1][2]))  ?>.php" class="media d-block room bg first-room" >
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                 
                      <img src="images/<?php echo room($id)[7][2][1] ?>" alt="<?php echo room($id)[4][2] ?>" title="<?php echo room($id)[1][2] ?>" class="img-fluid">

                <div style="position: absolute;bottom: 0px; width: 100%;background-color:rgba(0,0,0,0.5); padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px;  "><?php echo ucfirst(room($id)[1][2]) ?></strong>
                    </span>
                  </div>
                    
                  
                </div>
              </div>
                    
            </a>
            <a href="hotel-rooms/<?php echo strtolower(str_replace(" ","-", room($id)[1][3]))  ?>.php" class="media d-block room bg first-room" >
              <div style="position: relative; background-color: rgba(0,0,0,0.5);">
                 
                      <img src="images/<?php echo room($id)[7][3][1] ?>" alt="<?php echo room($id)[4][3] ?>" title="<?php echo room($id)[1][3] ?>" class="img-fluid">

                <div style="position: absolute;bottom: 0px;background-color:rgba(0,0,0,0.5); width: 100%; padding: 10px">
                  <div class="clearfix">
                    <span class="float-right" style="color: #fff; padding-right:10px">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </span>
                    <span class="float-left">
                      <strong style="color: #fff; padding: 10px; "><?php echo ucfirst(room($id)[1][3]) ?></strong>
                    </span>
                  </div>
                    
                  
                </div>
              </div>
                    
            </a>
            
          </div>
        </div>
      </div>
    </section>
   
    
    <section class="section-cover" data-stellar-background-ratio="0.5" style="color: black; background-image: url(images/<?php echo room($id)[7][1][2] ?>) ;">
      <div class="container">
        <div class="row justify-content-center align-items-center intro">
          <div class="col-md-9 text-center element-animate">
            <h2><?php echo settings($id)['footer_desp'] ?></h2>
            <p class="lead mb-5"></p>
            <div class="btn-play-wrap"><a href="https://vimeo.com/channels/staffpicks/93951774" class="btn-play popup-vimeo "><span class="ion-ios-play"></span></a></div>
          </div>
        </div>
      </div>
    </section>
    <!-- END section -->
    
    <section class=" bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
            <h2 class="heading">Gallery</h2>
          </div>
        </div>
        <div class="row ">
          <?php 

              $n=3;
              for ($i = 1; $i <=$n; $i++){
                echo '<div class="col-md-4"  >';?>
            <div class="post-entry">
              <a href="gallery/index.php"><img src="images/<?php echo gallery($id)[3][$i] ?>" alt="<?php echo gallery($id)[2][$i]; ?>"  title="<?php  echo gallery($id)[1][$i] ?>" class="img-fluid"></a>
              <div class="body-text">
                <div class="category"><?php  echo ucwords(gallery($id)[1][$i]); ?></div>
                <h3 class="mb-3"><a href="gallery/index.php"><?php echo ucwords(gallery($id)[1][$i]);  ?></a></h3>
                <p class="mb-4">
                  <?php
                      
                            $text = gallery($id)[2][$i];
                            $max =45;
                            $append= '<a href="gallery/index.php">..continue..</a>';
                            echo substr($text, 0, $max).$append;
                            
                              
                  ?> 
                </p>
              </div>
            </div>
         <?php echo '</div>' ?>
              <?php } ?>

          
         
         
          <div class="container">
            <div class="row justify-content-md-center">
              <div class="col-md-auto">
                <p><a href="gallery/index.php" class="btn btn-primary btn-sm">View All Gallery</a></p>
              </div>
            </div>
        </div>
        </div>
        
      </div>
    
    </section>
    <!-- END section -->
  <section class=" bg-light">
      <div class="container">
      <div class="row mb-5">
          <div class="col-md-12 heading-wrap text-center">
            <h2 class="heading">Facilities</h2>
          </div>
        </div>
  <div class="mt-5">
<div class="container">
            <div class="row ">
              <?php 
                  $t=2; 
                for ($i = 1; $i <=$t ; $i++) {
                       echo  '<div class="col-md-4" style=" margin-top:20px;margin-bottom: 10px;">';?>
            <div class="post-entry mh-100 d-inline-block p-2 " style="height:400px; background-color: #fff";>
              <a href="facilities/index.php"><img  src="images/<?php echo fac($id)[7][5][1]?>"  class="img-fluid" alt="<?php echo fac($id)[5][5] ?>" title="<?php echo fac($id)[1][5] ?>"></a>
              <div class="body-text" style="height: 100px; padding: 0px;">
                <div class="category"><?php echo fac($id)[1][5] ?></div>
                <h3 class=""><a href="facilities/index.php"><?php echo fac($id)[1][5] ?></a></h3>
                <p class="mb-4" style="height:100px;background-color: #fff"> <?php 
                            $text = fac($id)[5][5];
                            $max =45;
                            $append= '<a href="facilities/index.php">..continue..</a>';
                            echo substr($text, 0, $max).$append;?></p>
              </div>
            </div>
          <?php echo '</div>'; }?>
               


              
          
          <a href="facilities/index.php">
              <div class="col-md-4" style=" min-height: 400px; position: relative; background-image: url(images/<?php echo fac($id)[7][6][1]?>); margin: 20px 0px 40px 0px; padding: 0px 15px 0px 15px;">
                
                  <div style="position: absolute;font-size:24px; font-size: 24px;font-weight: 900;top: 50%;left: 25%; width: 100% ">
                    <a href="facilities/index.php" style="color: #fff">
                           <i class="fa fa-plus" ></i><strong > &nbsp;See more</strong>
                    </a>
                </div>
          </a>      
                
             
              </div>
        </div>
      </div>
      </div>
    </section>

<?php include('includes/footer.php'); ?>

  <?php
  
  $data = ob_get_contents();  

  ob_clean();  // clears buffer and closes buffering

 

  $data_en =str_replace("images/", "../images/", $data);

  $data_en =str_replace("assets/", "../assets/", $data_en);

  file_put_contents($id."/en/index.php", $data_en);

  file_put_contents($id."/index.php", $data);

  //final

  file_put_contents($folder.$id."/en/index.php", $data_en);

  file_put_contents($folder.$id."/index.php", $data);
  //echo $data;
  ?>
 